
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb 
    username: postgres 
    password: postgres@123   
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect